#!/bin/bash
# Install xylib-py
pip install xylib-py

# Install LaueTools without deps (no WX)
pip install --no-deps LaueTools

# Get GSAS II and build binary components
cd /tmp
wget -m -np https://subversion.xray.aps.anl.gov/pyGSAS/trunk/
mv /tmp/subversion.xray.aps.anl.gov/pyGSAS/trunk ~/GSASII
cd ~/GSASII/fsource
scons
